/** 心镜岛本地兜底点位（与后端 islandDefaults 保持同步） */
export const DEFAULT_ISLAND_SPOTS = [
  {
    id: 'cliff',
    name: '正念呼吸',
    tip: '正念呼吸',
    place: '云雾栈道',
    desc: '云雾缭绕的崖边栈道，风轻轻拂过。跟随引导做正念呼吸练习，让呼吸把心带回此刻。',
    cta: '去呼吸',
    cx: 72, cy: 15, hit: 10, labelSide: 'bottom',
    url: '/pages/breathing/select',
    enabled: true,
    sort: 10,
  },
  {
    id: 'lighthouse',
    name: '预约咨询师',
    tip: '预约咨询师',
    place: '云中灯塔',
    desc: '灯塔暖光为你照路。在这里浏览咨询师资料、预约时段，开启一段被看见的专业陪伴。',
    cta: '去预约',
    cx: 42, cy: 24, hit: 10, labelSide: 'bottom',
    url: '/pages/consultants/index',
    enabled: true,
    sort: 20,
  },
  {
    id: 'stairs',
    name: '学习培训',
    tip: '学习培训',
    place: '石阶小径',
    desc: '灯塔下的石阶拾级而上。查看考级报名与培训课程，一步一步走向专业成长。',
    cta: '去学习',
    cx: 59, cy: 37, hit: 9, labelSide: 'right',
    url: '/pages/learning/index',
    enabled: true,
    sort: 30,
  },
  {
    id: 'pavilion',
    name: '咨询工具',
    tip: '咨询工具',
    place: '湖畔沙滩',
    desc: '湖边柔软的沙岸，适合静静坐下来。打开情绪日记、CBT、梦工作等练习工具，慢慢整理内心。',
    cta: '去练习',
    cx: 52, cy: 61, hit: 10, labelSide: 'bottom',
    url: '/pages/homework/index',
    enabled: true,
    sort: 40,
  },
  {
    id: 'cave',
    name: '探索自己',
    tip: '心理测评',
    place: '湖心倒影',
    desc: '望向湖心的倒影，水面映出真实的你。完成专业心理测评，温柔地认识此刻的身心状态。',
    cta: '去测评',
    cx: 30, cy: 60, hit: 8, labelSide: 'bottom',
    url: '/pages/assessment/index',
    enabled: true,
    sort: 50,
  },
  {
    id: 'bridge',
    name: '咨询活动',
    tip: '咨询活动',
    place: '湖心石桥',
    desc: '石桥连起湖的两岸，也连起人与人。报名心理健康主题活动，与伙伴一起探索与成长。',
    cta: '去报名',
    cx: 40, cy: 48, hit: 7, labelSide: 'top',
    url: '/pages/activity/index',
    enabled: true,
    sort: 60,
  },
  {
    id: 'mirror',
    name: '心理图卡',
    tip: '心理图卡',
    place: '立镜之林',
    desc: '林间立着一面椭圆古镜。抽取心理图卡，让图像替你说话，看见内心未曾言说的风景。',
    cta: '去抽卡',
    cx: 78, cy: 56, hit: 10, labelSide: 'bottom',
    url: '/pages/ohcard/index',
    enabled: true,
    sort: 70,
  },
  {
    id: 'garden',
    name: '曼达拉',
    tip: '曼达拉',
    place: '花间草地',
    desc: '镜旁花开成片的草地，适合静心创作。用色彩画出曼达拉，在一圈一圈中找回平静与专注。',
    cta: '去创作',
    cx: 88, cy: 68, hit: 9, labelSide: 'left',
    url: '/pages/mandala/index',
    enabled: true,
    sort: 80,
  },
  {
    id: 'beast',
    name: '情绪怪兽',
    tip: '情绪怪兽',
    place: '瀑布洞窟',
    desc: '瀑布后的山洞里，住着你的情绪小怪兽。创建、喂养并陪伴它，学会看见情绪、与它和解。',
    cta: '去看看',
    cx: 26, cy: 75, hit: 11, labelSide: 'bottom',
    url: '/pages/monster/index',
    enabled: true,
    sort: 90,
  },
  {
    id: 'cabin',
    name: '个人中心',
    tip: '个人中心',
    place: '岸边木屋',
    desc: '岸边木屋灯火温暖，像属于你的小屋。查看预约、订单、券码与成就，安顿好自己的日常。',
    cta: '进入',
    cx: 72, cy: 84, hit: 10, labelSide: 'top',
    url: '/pages/profile/index',
    enabled: true,
    sort: 100,
  },
  {
    id: 'pier',
    name: '解压捏捏乐',
    tip: '解压捏捏乐',
    place: '湖畔栈桥',
    desc: '伸向湖面的小栈桥，适合歇一歇脚。玩玩捏捏乐，指尖一点戳破烦恼，让压力随泡泡散开。',
    cta: '去解压',
    cx: 48, cy: 91, hit: 9, labelSide: 'top',
    url: '/pages/squeeze/index',
    enabled: true,
    sort: 110,
  },
];

export function normalizeIslandSpots(list) {
  const fallback = DEFAULT_ISLAND_SPOTS.slice();
  if (!Array.isArray(list) || !list.length) return fallback;
  const out = list
    .filter(s => s && s.id && s.url && s.enabled !== false)
    .map((s, i) => ({
      id: s.id,
      name: s.name || s.id,
      tip: s.tip || s.name || s.id,
      place: s.place || '',
      desc: s.desc || '',
      cta: s.cta || '进入',
      cx: Number(s.cx),
      cy: Number(s.cy),
      hit: Number(s.hit) || 10,
      labelSide: s.labelSide || 'bottom',
      url: s.url,
      enabled: s.enabled !== false,
      sort: Number.isFinite(Number(s.sort)) ? Number(s.sort) : (i + 1) * 10,
    }))
    .sort((a, b) => (a.sort - b.sort) || String(a.id).localeCompare(String(b.id)));
  return out.length ? out : fallback;
}
